# Generated by Django 2.2.3 on 2019-08-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_no', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dept_details_App.Student')),
            ],
        ),
    ]
