# Generated by Django 2.2.3 on 2019-07-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_auto_20190705_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='school',
            name='sub',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=30)),
                ('st_sec', models.CharField(max_length=10)),
                ('st_roll_no', models.IntegerField()),
                ('sch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
        ),
    ]
