# Generated by Django 2.2.3 on 2019-07-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20190708_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sch_name',
            new_name='school_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='st_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='st_roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='st_sec',
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_roll_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_sec',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
