# Generated by Django 2.2.3 on 2019-07-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_auto_20190708_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('add', models.TextField()),
            ],
        ),
    ]
