# Generated by Django 2.2.3 on 2019-07-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books_details',
            table='BOOK',
        ),
    ]
