# Generated by Django 2.2.3 on 2019-07-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190705_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_details',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='books_details',
            table=None,
        ),
    ]
