# Generated by Django 2.2.3 on 2019-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20190822_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='st_sub',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
