# Generated by Django 2.2.3 on 2019-08-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='st_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
